### ISSUE TITLE
Stop building debs for Ubuntu 21.04

### ISSUE THREAD

**Issue by babolivier** [matrix-org/pkg-repo-configs#10]
Ubuntu 21.04 Hirsute Hippo reached its end of life on Jan 20: https://lists.ubuntu.com/archives/ubuntu-announce/2022-January/000276.html

We should stop building debs for it

**Comment by richvdh** [comment]
this is more a topic for https://github.com/matrix-org/synapse, where it is covered by https://github.com/matrix-org/synapse/issues/11525.

**Comment by babolivier** [comment]
Huh this is confusing. Let's close it in favour of matrix-org/synapse#11525 then.
